#!/usr/bin/env bash
#this script creates a story out of the /env/passwd file
while IFS= read -r line
do
	fields=$(echo "$line" | cut -d':' -f1,2,3,4,5,6,7)
	field_array=($fields)
	story="The user $field_array[0] is part of the $field_array[3] gang, lives in $field_array[5] and rides $field_array[6]. $field_array[2]'s place is protected by the passcode $field_array[1], more info about the user here: $field_array[4]"
	echo $story
done < /etc/passwd
