#!/usr/bin/env bash
#this script creates a story out of the /env/passwd file
while IFS=: read -r username password userid groupid info homedir shell
do
	story="The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $info"
	echo $story
done < /etc/passwd
