#!/usr/bin/env bash
#this script creates a story out of the /env/passwd file
while IFS=: read -r -a fields
do
    username="${fields[0]}"
    password="${fields[1]}"
    userid="${fields[2]}"
    groupid="${fields[3]}"
    info="${fields[4]}"
    homedir="${fields[5]}"
    shell="${fields[6]}"
    story="The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $info"
	echo "$story"
done < /etc/passwd
