#!/usr/bin/env bash
#this script will print different text at the 4th and 8th iteration
num=1
while ((num <= 10))
do
	if ((num == 4))
	then
		echo "bad luck"
	elif ((num == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((num ++))
done
	     