#!/usr/bin/env bash
#this script will display the minutes for 12 hours
num=0
while ((num <= 12))
do
    echo "Hour: $num"
    number=1
    while ((number <= 59))
    do
	echo $number
	((number ++))
    done
	  ((num ++))
done
      
