#!/usr/bin/env bash
#this script prints the contents of the current directory
for file in *
do
  # Check if the file is a regular file and not a directory
  if [ -f "$file" ]; then
  
    # Check if the file name contains a dash
    if [[ "$file" == *-* ]]; then
      name=$(echo "$file" | cut -d'-' -f2-)
      echo "$name"
    else
      echo "$file"
    fi
    
  fi
done
