#!/usr/bin/env bash
#this script prints the contents of the current directory
for file in *
do
        if [[ $file == .* ]]
        then
	    continue    
	elif [[ $file == *"-"* ]]
	then
		echo "${file#*-}"
	fi
done
