#!/usr/bin/env bash
# Content of 11-manage_my_process
PIDFILE=/var/run/my_process.pid

start() {
    ./manage_my_process &
    echo $! > $PIDFILE
    echo "manage_my_process started"
}

stop() {
    kill $(cat $PIDFILE)
    rm $PIDFILE
    echo "manage_my_process stopped"
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "\$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
esac
